# Generated by Django 3.2 on 2021-04-15 23:12

from django.db import migrations


def create_data(apps, schema_editor):
    Questions = apps.get_model('questions', 'Questions')
    Questions(title="Туториал по Django", desc="text001", tags=['tutorial', 'django']).save()
    Questions(title="Туториал по C++", desc="text002", tags=['tutorial', 'c++']).save()
    Questions(title="Туториал по C#", desc="text003", tags=['tutorial', 'c#']).save() 
    Questions(title="Практика по C#", desc="text004", tags=['practice', 'c#']).save() 
    Questions(title="Урок по JS", desc="text005", tags=['lesson', 'js']).save()  
    Questions(title="Практика по C++", desc="text006", tags=['practice', 'c++']).save() 

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
