# Generated by Django 3.2 on 2021-04-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions'),
        ('questions', '0003_questions2'),
    ]

    operations = [
    ]
